### ISSUE TITLE
Question: do these changes make sense if I want to always stay in my shell?

### ISSUE THREAD

**Issue by shmup** [susam/emfy#6]
```bash
#!/bin/sh
if [ "$#" -eq 0 ]
then
    echo "Starting new Emacs process ..." >&2
    emacs -nw
elif emacsclient -t -n "$@" 2> /dev/null
then
    echo "Opened $@ in Emacs server" >&2
else
    echo "Opening $@ in a new Emacs process ..." >&2
    emacs -nw "$@"
fi
```

Specifically, the `-nw` and `-t` for `emacs` and `emacsclient`. I'm just getting started, and I've tested and definitely this is opening files in my existing emacs server. I noticed it wasn't mentioned in the README, so I figure I'd get your input before I settle on it.

Thanks!

**Comment by susam** [comment]
Sorry, it took so long to take a look at this comment. Yes, these changes definitely make sense if the intention is to open the file in Emacs running within the terminal.

The README caters to the more common usage of Emacs in graphical mode running in a graphical desktop environment. But since you want to stay in the shell, these changes look good.
